# Generated by Django 3.2.8 on 2022-01-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220118_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
